[package]
name = "xdp"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
futures = "0.3.30"
libc = "0.2.155"
libbpf-rs = "0.23.1"
nix = "0.29.0"
prometheus = "0.13.4"
tokio = { version = "1.37.0", features = ["full"] }
warp = "0.3.7"